### ISSUE TITLE
Workaround for Visual Studio error using RestfulRouting View Engines

### ISSUE THREAD

**Issue by erictrade** [restful-routing/restful-routing#84]
I like the way RestfulRouting View Engines organizes the views on folders, when using areas. I'm using it, but Visual Studio, and Resharper, is annoying me indicating as error, saying that the view doesn't exist.
I understand why. It's not where it's expecting.
Is there any way to overwrite the Visual Studio IDE and Resharper behavior when looking for views?

Thanks in advance!

**Comment by khalidabuhakmeh** [comment]
Sorry, there is not a current workaround for this. It is a bummer. I talked to a few people at JetBrains and they said they wouldn't support ViewEngines in ReSharper. That was years ago, so I'm not sure if they might have a different view point today.

**Comment by erictrade** [comment]
No problem, thank you for your attention!
