### ISSUE TITLE
http://restfulrouting.com cannot be found

### ISSUE THREAD

**Issue by mbischoff** [restful-routing/restful-routing#86]
Is this project no longer active? I tried to read about it, but http://restfulrouting.com cannot be found.

**Comment by daniellillja** [comment]
I was able to get a cache of it at https://web.archive.org/web/20150720065419/http://restfulrouting.com/

**Comment by khalidabuhakmeh** [comment]
Sorry, I took the site down because it was hosted on my Azure account and it was starting to cost money. You can run the same documentation site by pulling the project down.

**Comment by khalidabuhakmeh** [comment]
You should be able to access the new documentation site at http://restfulrouting.com now.
