### ISSUE TITLE
Security: route debugging is always accessible if a fallback route is defined

### ISSUE THREAD

**Issue by TheCloudlessSky** [restful-routing/restful-routing#87]
Given the default MVC route configuration with a fallback route, it is possible to visit `/routedebug` or `/routedebug/index` and view all routes (even unauthenticated users). For example:

```csharp
public class RouteConfig
{
    public class MyCustomRoutes : RouteSet
    {
        public override void Map(IMapper map)
        {
            // Route config here... but don't call map.DebugRoute("routedebug");
        }
    }

    public static void RegisterRoutes(RouteCollection routes)
    {
        routes.MapRoutes<MyCustomRoutes>();

        routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

        // Fallback.
        routes.MapRoute(
            name: "Default",
            url: "{controller}/{action}/{id}",
            defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
        );
    }
}
```

This is because the fallback route finds the `RouteDebugController`.

## Workaround

Before the fallback route, add the following:

```csharp
routes.IgnoreRoute("routedebug/{*action}");
```

This blocks `/routedebug` and `/routedebug/index` from being accessible (unless you explicitly set `map.DebugRoute("routedebug")`).

## Fix

I'd gladly submit a PR to fix this, but I wasn't sure the best approach for the community:

1. A way to secure visiting the `RouteDebugController` (and have it hardened by default) using something like:

    ```csharp
    interface IRouteDebugPermission
    {
        bool HasPermission(ControllerContext context);
    }

    class AllowRouteDebugPermission : IRouteDebugPermission
    {
        public bool IsGranted(ControllerContext context)
        {
            return true;
        }
    }

    class DenyRouteDebugPermission : IRouteDebugPermission
    {
        public bool IsGranted(ControllerContext context)
        {
            return false;
        }
    }

    class RouteDebugController : Controller
    {
        // Customized via DebugRoute(), for example.
        internal static IRouteDebugPermission Permission { get; set; } = new DenyRouteDebugPermission();

        public ActionResult Index()
        {
            if (!Permission.IsGranted(ControllerContext))
            {
                return HttpNotFound();
            }
            // ...snip...
        }
    }

    class Mapper : IMapper
    {
        // ...snip...
        public void DebugRoute(string path)
        {
            AddMapper(new DebugRouteMapper(path));
            DebugRouteController.Permission = new AllowRouteDebugPermission();
        }

        public void DebugRoute(string path, IDebugRoutePermission debugRoutePermission)
        {
            AddMapper(new DebugRouteMapper(path));
            DebugRouteController.Permission = debugRoutePermission;
        }
    }
    ```
Adding a new overload for `DebugRoute` would be a breaking change to the interface (I'm all for bumping the major version and following semantic versioning since this issue is a security hole!). Or, we could implement it as an extension method so it's not a breaking change, for now.

2. When setting the routes on the `RouteTable` with `MapRoutes()`, it'll check if some sort of fallback is defined or if route debug hasn't been called with `DebugRoute()` and explicitly set the workaround (this is hacky, though).

**Comment by khalidabuhakmeh** [comment]
Hello, I like the code you have but I'm not sure I want to change the current behavior due a few things. Please let me explain. The problem you described is not a problem with Restful Routing as much as a problme using the default route provided by the ASP.NET MVC template. **Using the default route is bad practice to begin with**. The problem you explained would happen with **any** controller found in a secondary assembly, which is annoying on many levels and is a known issue with ASP.NET MVC. 

I believe the proper workaround is **not to use the default route provided by the template.** If you are using Restful Routing there are ways to register more specific routes that don't expose the problem you describe.

## Side Conversation

The next major bump for Restful Routing will be to support ASP.NET Core 1.0, which I am waiting for the API to stabilize to so I can start migrating this code base to it.

For the next version of Restful Routing, I can see utilizing more middleware components for debugging routes rather than leaning on Controllers since **Routing** is now a middleware / cross cutting concern rather than an MVC specific feature.

**Comment by TheCloudlessSky** [comment]
I definitely agree about *not* using the default route provided by the template (we're not). However, it should be understood that a lot of MVC users (especially novice ones) won't understand that the fallback route is dangerous (so they won't remove it). Especially when it's backed into MVC templates by default! I don't think we can expect most people to change the default routing.

There's no warning on the site (even though it's down) or in the README that advises how to work around this security hole. I believe that this library should at least *attempt* to be secure by default (especially when it's exposing sensitive infrastructure information).

The change that I proposed doesn't break existing functionality. The `map.DebugRoute("routedebug")` will still work as expected.

PS - I agree about using a middleware component for ASP.NET Core 1.0. However, I don't think every project is going to upgrade their solutions right away since it's a huge upgrade. Therefore, I still believe that this is an important thing to fix (even if it's the last release for non-Core 1.0).

**Comment by khalidabuhakmeh** [comment]
new documentation site at http://restfulrouting.com specifically calls out the default route.

**Comment by TheCloudlessSky** [comment]
:+1: That's fine for now.
