### ISSUE TITLE
Variable resource name

### ISSUE THREAD

**Issue by exalted** [restful-routing/restful-routing#89]
Hi, I wonder if is it possible obtaining a route table similar to what's below?

```
http://example.com/
http://example.com/{organization}
http://example.com/{organization}/customers
http://example.com/{organization}/customers/{id}
```

The "interesting" thing above is that the URL for a given organization is given by it's name (as a parameter) rather than something like `http://example.com/organizations/{id}`.

Thanks.

**Comment by exalted** [comment]
I guess Rails (as an example) allows "empty" paths in routes, so we should be able to do something like:

```cs
map.Resources<OrganizationsController>(
                x =>
                {
                    x.Path(""); // !!!

                    x.Resources<CompaniesController>();
                });
```

**Comment by khalidabuhakmeh** [comment]
I'll have to think about this one, but off the top of my head I would just setup a `Path` and not use the `Resources` registration.

**Comment by exalted** [comment]
:+1:

**Comment by khalidabuhakmeh** [comment]
Crazy thought, I haven't tried this, but maybe you could.

``` csharp
map.Resources<OrganizationsController>(
  x =>
  {
    x.As("{organization}");
    x.Resources<CompaniesController>();
  });
```

Note that that **As** method is used, and passes in a `{organization}` placeholder, instead of a string.

**Comment by exalted** [comment]
@khalidabuhakmeh sadly, as it unfortunately happens in these cases, I had to move along without restful-routing in my project (actually to be 100% honest, I still use `ApplicationController#RespondTo` with `FormatResult`, which is a :star: ).

This all is to say that I don't have a project to test your suggestions out and I am glad there may be workarounds (?).

Thanks.

**Comment by khalidabuhakmeh** [comment]
That's a bummer, but I'm glad you found something positive out of the project. Good luck with your project.
