### ISSUE TITLE
Format routes not resolving

### ISSUE THREAD

**Issue by yoccodog** [restful-routing/restful-routing#93]
I'm building a small ASP.NET MVC app and started using restful-routing because it makes sense :) 

I want to use formatted routes but I'm running into a problem though where the format field is not being populated or processed on my requests. Here is my route definition:

`map.Resources<UsersController>(users =>
{
  users.WithFormatRoutes();
});`

When I browse to:

`http://localhost:55386/users/1`

I can see that the UsersController and the RespondTo code is being hit and a result is returned. But when I browse to:

`http://localhost:55386/users/1.json`

I get a 404 and my breakpoints in the UsersController are not hit.

I've check the route debugger and the routes that show up are those that I expect, e.g. some with `users.{format}` and some without. 

This is running version 1.6.0 with a target of .NET 4.5.2. Any help would be appreciated!

**Comment by khalidabuhakmeh** [comment]
What does your controller action look like? 

It should look like this: http://restfulrouting.com/#format-result

**Comment by yoccodog** [comment]
I tried to follow that example. Here's what it looks like:

```
    public ActionResult Show(int? id)
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        User user = db.Users.Find(id);

        if (user == null)
        {
            return HttpNotFound();
        }

        return RespondTo(format => {
            format.Html = () =>
            {
                return Json(JsonConvert.SerializeObject(user, 
                    Formatting.Indented, 
                    new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects }), 
                    JsonRequestBehavior.AllowGet);
            };
            format.Json = () =>
            {
                return Json(JsonConvert.SerializeObject(user, 
                    Formatting.Indented, 
                    new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects }),
                    JsonRequestBehavior.AllowGet);
            };
        });
    }
```

I have both the Html and Json formats returning JSON as a test. If I put a breakpoint on the first line of this function, though, it never gets hit when I specify a format in the url.

**Comment by khalidabuhakmeh** [comment]
Make sure you are running all requests through the ASP.NET Pipeline. IIS is seeing the format and thinking it is a file on disk. Something I will update in the documentation as well.

``` xml
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
  </system.webServer>
```

![](https://cdn.meme.am/instances/500x/69309953.jpg)

**Comment by khalidabuhakmeh** [comment]
I updated the documentation and pushed it up. Thank you for finding this and bringing it to my attention.

**Comment by yoccodog** [comment]
That did the trick. Thanks for your help!
